-- AlterTable
ALTER TABLE `Configs` MODIFY `secondDay` VARCHAR(3) NULL DEFAULT 'ALL',
    MODIFY `secondTime` VARCHAR(4) NULL DEFAULT '0000',
    MODIFY `thirdDay` VARCHAR(3) NULL DEFAULT 'ALL',
    MODIFY `thirdTime` VARCHAR(4) NULL DEFAULT '0000',
    MODIFY `firstDay` VARCHAR(3) NULL DEFAULT 'ALL',
    MODIFY `firstTime` VARCHAR(4) NULL DEFAULT '0000';
