-- AlterTable
ALTER TABLE `Configs` ADD COLUMN `dnsEth` VARCHAR(50) NULL,
    ADD COLUMN `getwayEth` VARCHAR(50) NULL,
    ADD COLUMN `ipEth` VARCHAR(50) NULL,
    ADD COLUMN `modeEth` CHAR(1) NULL DEFAULT '0',
    ADD COLUMN `muteDoor` CHAR(1) NOT NULL DEFAULT '0',
    ADD COLUMN `muteLong` CHAR(1) NOT NULL DEFAULT '0',
    ADD COLUMN `subNetEth` VARCHAR(50) NULL;
